CC=gcc
CFLAGS=-g -std=gnu99 -I. 

lervisnh-shell : main.c command.c string_parser.c
	$(CC) main.c command.c string_parser.c -o lervisnh-shell $(CFLAGS)

# test_string_parser : test_string_parser.c string_parser.c
# 	$(CC) test_string_parser.c string_parser.c -o test_string_parser $(CFLAGS)
